[package]
name = "day13"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
regex = "1.11.1"
nalgebra = "0.33.2"

[build-dependencies]
ureq = { version = "2.10.1", features = [] }
